apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: pi
spec:
  slotsPerWorker: 4
  runPolicy:
    cleanPodPolicy: Running
  sshAuthMountPath: /home/mpiuser/.ssh
  mpiImplementation: Intel
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
            - image: bodoaidocker/pi:latest
              imagePullPolicy: Always
              name: mpi-launcher
              securityContext:
                runAsUser: 1000
              args:
                - mpirun
                - -n
                - "8"
                - python
                - /home/mpiuser/pi.py

    Worker:
      replicas: 2
      template:
        spec:
          containers:
            - image: bodoaidocker/pi:latest
              imagePullPolicy: Always
              name: mpi-worker
              securityContext:
                runAsUser: 1000
              command:
              args:
                - /usr/sbin/sshd
                - -De
                - -f
                - /home/mpiuser/.sshd_config
  
              
             