apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: {{ .Values.name }}
spec:
  slotsPerWorker: {{ .Values.slotsPerWorker }}
  runPolicy:
    cleanPodPolicy: Running
  sshAuthMountPath: /home/mpiuser/.ssh
  mpiImplementation: Intel
  mpiReplicaSpecs:
    Launcher:
      replicas: {{ .Values.launcher.replicas}}
      template:
        spec:
          containers:
            - image: {{ .Values.image }}
              imagePullPolicy: Always
              name: mpi-launcher
              securityContext:
                runAsUser: 1000
              args:
                - mpirun
                - -n
                - "8"
                - python
                - {{ .Values.launcher.path }}

    Worker:
      replicas: {{ .Values.worker.replicas }}
      template:
        spec:
          # Replaced shared memory with an empty directory
          # to avoid the docker shared memory limit
          # (see https://stackoverflow.com/questions/46085748/define-size-for-dev-shm-on-container-engine/46434614#46434614)
          volumes:
          - name: dshm
            emptyDir:
              medium: Memory
          containers:
            - image: {{ .Values.image }}
              imagePullPolicy: Always
              name: mpi-worker
              resources:  
                requests:
                   memory: {{ .Values.worker.memory }}
                   cpu: {{ .Values.worker.cpu }}

              securityContext:
                runAsUser: 1000
              command:
              args:
                - /usr/sbin/sshd
                - -De
                - -f
                - /home/mpiuser/.sshd_config
          
